PrimeFaces.locales['pt_BR'] = {
	        closeText: 'Fechar',
	        prevText: 'Anterior',
	        nextText: 'Próximo',
	        monthNames: ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
	        monthNamesShort: ['Jan', 'Feb', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'],
	        dayNames: ['Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'],
	        dayNamesShort: ['Dom', 'Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb'],
	        dayNamesMin: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
	        weekHeader: 'Semana',
	        firstDay: 1,
	        isRTL: false,
	        showMonthAfterYear: false,
	        yearSuffix: '',
	        timeOnlyTitle: 'Apenas hora',
	        timeText: 'Tempo',
	        hourText: 'Hora',
	        minuteText: 'Minuto',
	        secondText: 'Segundo',
	        currentText: 'Fechar atual',
	        ampm: false,
	        month: 'Mês',
	        week: 'Semana',
	        day: 'Dia',
	        allDayText: 'Todo o dia'
};